### ISSUE TITLE
Picker does not respond when in Interactable.View

### ISSUE THREAD

**Issue by jirkaakres** [wix/react-native-interactable#32] opened 2017-03-21 10:43 UTC
So I have a `Picker` component inside an `Interactable.View` (it is for a pull-down screen with customer billing information, works something like notifications pull-down area on iOS). The `Picker `does not respond to touches, the `Interactable.View` just trembles and that's all. 
I have checked that if I just replace the `Interactible.View` with regular `View`, all works well.
Am I doing something wrong or is it a bug in the library?
Thanks

**Comment by talkol** [comment] 2017-03-21 10:58
Most likely a bug in the library. Handling of touches is pretty complex. We can have a scroll view holding an interactable that can hold a scroll view. The mitigation is not trivial.

The naive example we currently support is this:
https://github.com/wix/react-native-interactable/blob/master/example/src/HandleTouches.js

I will add more complex touch examples, including your picker example so we can figure it out.

**Comment by talkol** [comment] 2017-03-21 23:25
I added a test example in the commit above, here it is:
https://github.com/wix/react-native-interactable/blob/master/example/src/TouchesInside.js

you can run it inside the example app

just tested it on iOS and it actually works very nicely with the touches inside the interactable.view

can you please try it out?

**Comment by jirkaakres** [comment] 2017-03-23 11:35
On iOS it works well. I had some problems when resizing the container, but overall it was ok.
On Android however.. The only thing that works is the button. Everything else triggers the view movement.

**Comment by talkol** [comment] 2017-03-24 15:24
The touches issues on Android will be fixed by @LoyalBlocks-tzachi next week

**Comment by LoyalBlocks-tzachi** [comment] 2017-03-27 14:26
Hi guys! I fixed most of the Android touch issues in this branch: https://github.com/wix/react-native-interactable/tree/androidFixes

I'll appreciate if you can give feedback before I merge to master

The issue that still remain unresolved (I'm still working on it) is horizontal scroll inside horizontal moving interactable (or anything with horizontal drag like a slider)

**Comment by talkol** [comment] 2017-03-30 20:12
Hi guys, this was pushed into master and published (v0.0.7). Please confirm the fix so we can close this issue

**Comment by talkol** [comment] 2017-03-30 20:15
Let's do this the other way around.. I'll close and if the issue is still there please reopen

**Closed by talkol** 2017-03-30 20:15 UTC
