### ISSUE TITLE
Invariant Violation

### ISSUE THREAD

**Issue by TheDutchCoder** [wix/react-native-interactable#185] opened 2018-02-12 14:57 UTC
When importing this library I get an Invariant Violation:

```js
import Interactable from 'react-native-interactable'

class ListItem extends React.component {
  render() {
    return (
      <Interactable.View horizontalOnly={true}>
        <View>
          <Text>Drag me!</Text>
        </View>
      </Interactable.View>
    )
  }
}
```

Screenshot:
![image](https://user-images.githubusercontent.com/1668207/36102627-dfc409c4-0fda-11e8-8781-83833b8979dc.png)

**Comment by mafiusu** [comment] 2018-02-16 11:02
I'm having the same issue after upgrading to the latest React Native version.

**Comment by lfalcao** [comment] 2018-02-16 15:09
It's working here...

- react 16.2.0
- react-native 0.52.2
- react-native-interactable 0.1.10

`import React from 'react'
import {
  View,
  Text
} from 'react-native'
import Interactable from 'react-native-interactable'

export class Item extends React.Component {
  render() {
    return (
      <Interactable.View horizontalOnly={true}>
        <View>
          <Text>Drag me!</Text>
        </View>
      </Interactable.View>
    )
  }
}`

**Comment by TheDutchCoder** [comment] 2018-02-16 15:20
That's an older version of react native. We're using 0.53.0

**Comment by lfalcao** [comment] 2018-02-18 15:03
I can reproduce this only when I unlink the native library. So try to unlink and link to see if it works...

Tested again and working with: 
- react-native@0.53.0
- react-native@0.54.0-rc.3

**Comment by ivanesi** [comment] 2018-02-23 11:28
the same
react-native: 0.53.2

**Comment by joaom182** [comment] 2018-02-25 06:22
+1

**Comment by phillip055** [comment] 2018-03-15 05:05
Any update?

**Comment by mhayta** [comment] 2018-03-26 13:37
+1

**Comment by dekemega** [comment] 2018-04-14 07:36
+1

**Comment by seanyusa** [comment] 2018-04-23 17:07
I had this issue just now and found out that it was erroring because I forgot running `pod install` in the `ios` directory

**Comment by Inbal-Tish** [comment] 2018-11-05 10:13
Please make sure to link native properly. In any case I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce the issue.

Thanks for your contribution.

**Closed by Inbal-Tish** 2018-11-05 10:13 UTC

**Comment by tunm1228** [comment] 2019-04-16 10:27
Please check Libraries Xcode
