### ISSUE TITLE
Could not resolve all dependencies for configuration ':app:_debugApk'.

### ISSUE THREAD

**Issue by singhalpk** [wix/react-native-interactable#142] opened 2017-08-18 09:28 UTC
![image](https://user-images.githubusercontent.com/22507924/29452964-b3369304-8425-11e7-81dd-716adb29a8e7.png)

**Comment by jp928** [comment] 2017-08-18 10:40
please attach your setting.gradle and build.gradle as well

**Comment by andresgala** [comment] 2017-08-21 01:46
This is my build.gradle file:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}

```
And this my settings.gradle file:
```
rootProject.name = 'example'

include ':app'

include ':react-native-interactable'
project(':react-native-interactable').projectDir = new File(rootProject.projectDir, '../../android')

```
Im getting the same error as @singhalpk

**Comment by jp928** [comment] 2017-08-21 02:38
@singhalpk @andresgala 
This is caused by the postInstall in the package.json in this library. If you wanna to research deeper, you may need to check the package.json in this library:
```json
"postinstall": "ln -sf lib/{ios,android} ."
```

which is trying to create a softlink from ./node_modules/react-native-interactable/lib/android to the project root folder. Unfortunately, this is not a valid windows command. Thus, the fix is quite simple, you can modify your settings.gradle to fix the path as below:

```javascript
include ':react-native-interactable'
project(':react-native-interactable').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-interactable/lib/android')
```

**Comment by jp928** [comment] 2017-08-21 02:47
[Same issue](https://github.com/wix/react-native-interactable/issues/140)

**Comment by matthieupinte** [comment] 2017-09-25 16:44
Hi,

Keep having this issue :
```
Creating configuration testReleaseProvided
Creating configuration testReleaseWearApp
Creating configuration testReleaseAnnotationProcessor
Parsing the SDK, no caching allowed
file or directory '/Users/me/Works/myApp/node_modules/react-native-interactable/lib/android/libs', not found
file or directory '/Users/me/Works/myApp/node_modules/react-native-interactable/lib/android/libs', not found
file or directory '/Users/me/Works/myApp/node_modules/react-native-interactable/lib/android/libs', not found
file or directory '/Users/me/Works/myApp/node_modules/react-native-interactable/lib/android/libs', not found
Using incremental javac compilation.
file or directory '/Users/me/Works/myApp/node_modules/react-native-interactable/lib/android/libs', not found
file or directory '/Users/me/Works/myApp/node_modules/react-native-interactable/lib/android/libs', not found
Not using incremental javac compilation.
Using incremental javac compilation.
file or directory '/Users/me/Works/myApp/node_modules/react-native-interactable/lib/android/libs', not found
file or directory '/Users/me/Works/myApp/node_modules/react-native-interactable/lib/android/libs', not found
Not using incremental javac compilation.
file or directory '/Users/me/Works/myApp/node_modules/react-native-interactable/lib/android/libs', not found
file or directory '/Users/me/Works/myApp/node_modules/react-native-interactable/lib/android/libs', not found
```

Tried use `0.1.3` & `0.1.2` and without or without your `settings.gradle` updates :
```
include ':react-native-interactable'
project(':react-native-interactable').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-interactable/lib/android')
```
or 
```
include ':react-native-interactable'
project(':react-native-interactable').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-interactable/android')
```

without success... :/

**Comment by isaachinman** [comment] 2018-06-06 14:38
What could possibly motivate the devs on this project to introduce the potential for failure of a softlink for seemingly no good reason whatsoever? What's wrong with having `/lib/` in the path?

**Comment by GabrielScalici** [comment] 2018-08-31 19:42
in terminal install npm again: 
$npm install

**Comment by anubhav19rai** [comment] 2018-09-12 05:53
Please run this command **react-native upgrade**. This command will ask replace existing file or not. If you    want to replace a particular file press Y and hit enter button or press N. After completing this command than run command  **react-native link**. This command will link all dependencies than you can run command **react native run-android /ios**. This issue create when you uninstall some dependencies so sometimes  it do not update build files like setting.gradle build.gradle etc.

**Comment by Inbal-Tish** [comment] 2018-11-05 10:23
I am closing the issue as a part of an effort to cleanup and revive the project. If this issue persists after v1.0.0, you are more than welcome to reintroduce the issue.

Thanks for your contribution.

**Closed by Inbal-Tish** 2018-11-05 10:23 UTC

**Comment by SangramMemane** [comment] 2019-04-19 10:13
> in terminal install npm again:
> $npm install

solve my issue thank u sir
